global:
    scrape_interval: 15s

alerting:
    alertmanagers:
        - static_configs:
              - targets:
                    - alertmanager:9093

scrape_configs:
    - job_name: "prometheus"
      static_configs:
          - targets: ["localhost:9090"]
          # monitor的9090

    - job_name: "docker"
      static_configs:
          - targets: ["cadvisor:8080"]

    # 其他docker容器设定端口

    - job_name: "etl"
      static_configs:
          - targets: ["etl:8888"]
      metrics_path: "/metrics"
      scrape_interval: 10s

    - job_name: "deploy"
        static_configs:
            - targets: ["deploy:8080"]
        metrics_path: "/metrics"
        scrape_interval: 10s